Repository LouisSeranne/DICJ_Stimulus_A23, pull requests merged in 2023-09, with the labels that each got.

#6 01FeatureYohan
  StimulusFrontEnd/Components/FooterEtudiantComponent.razor
  StimulusFrontEnd/Components/GrapheComponent.razor
  StimulusFrontEnd/Components/HeaderComponentEtudiant.razor
  StimulusFrontEnd/Components/TheorieComponent.razor
  StimulusFrontEnd/Components/TheorieComponents/Exercice.razor
  StimulusFrontEnd/Pages/PageGroupe.razor
  StimulusFrontEnd/Pages/PageNoeud.razor
  StimulusFrontEnd/Program.cs
  StimulusFrontEnd/Shared/EtudiantLayout.razor
  StimulusFrontEnd/Shared/MainLayout.razor
  StimulusFrontEnd/StimulusFrontEnd.csproj
  StimulusFrontEnd/appsettings.json
Labels: enhancement

#7 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#33 Fix affichage noeuds
  StimulusFrontEnd/Components/GrapheComponent.razor
  StimulusFrontEnd/Components/HeaderComponentEtudiant.razor
  StimulusFrontEnd/Shared/EtudiantLayout.razor
Labels: fix

#81 Fix css important
  StimulusFrontEnd/Components/TheorieComponents/Exercice.razor
  StimulusFrontEnd/wwwroot/css/site.css
Labels: 2, enhancement, fix, web
